#!/bin/bash

initial_dir=$(pwd)

src=$(dirname $0)
src=$(cd $src;pwd)
source $src/testing-common-vault.sh

create_test_dir

write_text() {
    echo "text:$1" > $2
}

write_random() {
    dd if=/dev/urandom of=$3 bs=$1 count=$2 2>>$test_err
}

dump_curdir_tree() {
    for f in $(find | sort); do
        if [ -d $f ]; then
            echo "d:$f"
        elif [ -f $f ]; then
            if [ "$(head -c 5 $f)" == "text:" ]; then
                echo "f:$f:$(cat $f)"
            else
                echo "f:$f:md5:$(md5sum -b $f)"
            fi
        elif [ -L $s ]; then
            echo "d:$f"
        fi
    done
}

check_home_storage_same_filenames() {
    cd $storage && dump_curdir_tree > $test_dir/find_src
    cd $test_home/$(basename $storage) && dump_curdir_tree > $test_dir/find_dst
    diff $test_dir/find_src $test_dir/find_dst || error 11 "Tree is not fully copied?"
}

NEXT_TEST "Basic copy"
create_test_dirs 1
mkdir -p $storage/d0
touch $storage/f1
write_text "2" $storage/f2
write_text "0123456789 0123456789" $storage/f3
write_random 1024 1058 $storage/big_f4
vault-copy -a import -r $storage $test_home || error 21 "copy existed with $?"
check_home_storage_same_filenames

NEXT_TEST "Copy when exists"
create_test_dirs 2
# src
mkdir -p $storage/d0
touch $storage/f1
write_text "2" $storage/f2
write_text "0123456789 0123456789" $storage/f3
write_random 1024 1058 $storage/big_f4
# dst
mkdir -p $test_home/d0
write_text "before" $test_home/f1
write_text "before" $test_home/f2
write_text "before" $test_home/f3
write_random 1024 512 $test_home/big_f4
vault-copy -a import -r $storage $test_home || error 22 "copy existed with $?"
check_home_storage_same_filenames
