#!/bin/bash

src=$(dirname $0)
src=$(cd $src;pwd)
source $src/vault-misc $src

init_root_and_enter

show_help() {
    echo "Usage: $0 <src-branch> <new-branch-name> <after-commit-hook>" >&2
}

if [ $# -lt 2 ]; then
    show_help
    exit 1
fi
src_branch=$1
new_branch=$2
after_commit_hook=$3
git reset --hard && git clean -fd || error 10 "Can't reset/clean"
git checkout -b $new_branch anchor || error 11 "Can't checkout branch"

for h in $(git log --format=%H anchor..$src_branch | tac); do
    git-commit-copy $h || error 16 "Can't copy commit"
    if [ "x$after_commit_hook" != "x" ]; then
        $after_commit_hook
        git commit --amend --allow-empty --no-edit
    fi
    git-tag-copy -t $new_branch/ $h || error 17 "Can't copy tag"
done

git reset --hard
git clean -fd
echo "branch-copy:$src_branch:$new_branch" > .vault.state
